[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "argparse>=1.4.0",
    "duckdb>=1.4.2",
    "numpy==1.26.4",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "pyspark==4.0.1",
    "python-levenshtein>=0.27.3",
    "ruff>=0.14.6",
    "thefuzz>=0.22.1",
]
